name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Define the environment variables for GitHub secrets (automatically handled by GitHub Actions)
    - name: Set up environment variables for secrets
      run: |
        echo "BUCKET_SA=${{ secrets.BUCKET_SA }}" >> $GITHUB_ENV
        echo "DEV_SA=${{ secrets.DEV_SA }}" >> $GITHUB_ENV

    - name: Init
      run: terraform init -backend-config="credentials=${{ secrets.BUCKET_SA }}"

    - name: Validate
      run: terraform validate

    - name: Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
