name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./envs/dev

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Configure Google Cloud Credentials (Service Account 1)
      run: echo "${{ secrets.BUCKET_SA }}" > ../../envs/dev/bucket_sa.json
      shell: bash

    - name: Configure Google Cloud Credentials (Service Account 2)
      run: echo "${{ secrets.DEV_SA }}" > ../../envs/dev/dev_proj.json
      shell: bash

    - name: Init
      run: terraform init # -backend-config="../../backend/backend.tf"

    - name: Validate
      run: terraform validate

    - name: Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
